name: tisini
description: "tisini â€” mobile wallet + payments app for African SMEs and gig workers."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  camera: ^0.11.0
  connectivity_plus: ^6.1.0
  crypto: ^3.0.7
  csv: ^6.0.0
  dio: ^5.7.0
  drift: ^2.22.0
  envied: ^1.0.0
  file_picker: ^8.1.0
  firebase_analytics: ^11.3.0
  firebase_messaging: ^15.1.0
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.2
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.3
  freezed_annotation: ^2.4.4
  go_router: ^14.6.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  local_auth: ^2.3.0
  mobile_scanner: ^7.1.4
  path_provider: ^2.1.5
  phosphor_flutter: ^2.1.0
  qr_flutter: ^4.1.0
  riverpod_annotation: ^2.6.1
  share_plus: ^10.1.0
  shared_preferences: ^2.3.3
  sqlite3_flutter_libs: ^0.5.0
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.13
  drift_dev: ^2.22.0
  envied_generator: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  riverpod_generator: ^2.6.2
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
